spring:
  profiles:
    active: dev
  application:
    admin:
      enabled: true
    name: input-output-service
  datasource:
    hikari:
      password: root
      username: root
      jdbc-url: jdbc:mysql://localhost:3306/birzha?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      connection-test-query: SELECT 1 FROM DUAL
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  redis:
    host: 172.10.10.236
    port: 6379

slave:
  datasource:
    hikari:
      password: root
      username: root
      jdbc-url: jdbc:mysql://localhost:3306/birzha?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      connection-test-query: SELECT 1 FROM DUAL
      driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://172.50.50.245:8090/eureka}
    should-unregister-on-shutdown: true
    registry-fetch-interval-seconds: 5
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 10
    metadata-map:
      startup: ${random.int}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS


mail:
  mail_support:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    user: exrates.dev@gmail.com
    password: setarxe123
  mail_mandrill:
    host: smtp.mandrillapp.com
    port: 587
    protocol: smtp
    user: Currency
    password: PsQhkDq7dB8Zn3qAserRTw
  mail_info:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    user: exrates.dev@gmail.com
    password: setarxe123
    allowedOnly: true
    allowedEmails: golvazin@gmail.com,avto12@i.ua,wayfarer2006@ukr.net,yagi7337@gmail.com,yagi3773@gmail.com,vlad.dziubak@gmail.com,nikita.dmytrenko@upholding.biz,oleg.kostiukevych@upholding.biz
  default_mail_type: gmail

telegram:
  bot:
    url: https://t.me/exrates_local_test_bot
    key: 467357916:AAFNnf9iLW3cVSRA_EPwiuU74KYgjKo-VDc
    username: exrates_local_test_bot
    name: exrates_local_test

epochta:
  URL: http://api.atompark.com/members/sms/xml.php
  login: sell@exrates.top
  password: 1exMeBNhybYfV

session:
  checkPinParam: l_checkPin
  authenticationParamName: authentication
  passwordParam: l_password

invoice:
  blockNotifyUsers: true

advcash:
  url: https://wallet.advcash.com/sci/
  accountId: exratesnew@gmail.com
  payeeName: Exrates
  paymentSuccess: http://dev.exrates.tech/merchants/advcash/payment/success
  paymentFailure: http://dev.exrates.tech/merchants/advcash/payment/failure
  paymentStatus: https://exrates.me/merchants/advcash/payment/status
  USDAccount: U143527856819
  EURAccount: E971693091461
  payeePassword: s3Jb8$P69o
  ipWhiteList: 77.109.141.170;91.205.41.208;94.242.216.60;193.93.79.99;

perfectmoney:
  url: https://perfectmoney.is/api/step1.asp
  accountId: S404847
  accountPass: 66RwHvFG
  payeeName: Exrates
  paymentSuccess: http://193.93.79.99:9000/merchants/perfectmoney/payment/success
  paymentFailure: http://193.93.79.99:9000/merchants/perfectmoney/payment/failure
  paymentStatus: http://193.93.79.99:9000/merchants/perfectmoney/payment/status
  USDAccount: U16666480
  EURAccount: E15714655
  alternatePassphrase: 17T92E7OUsrEPkcqnnATClUnH
  ipWhiteList: 77.109.141.170;91.205.41.208;94.242.216.60;78.41.203.75;

referral:
  url: localhost:8080/register?ref=

btcInvoice:
  blockNotifyUsers: true

upload:
  userFilesDir: c:/Users/Public/upload/
  userFilesLogicalDir: /userFiles

ban:
  short:
    attempts:
      num: 3
      period: 60
    time: 60
  long:
    attempts:
      num: 6
      period: 3000
    time: 300

stellar:
  slt:
    emitter: GC7Q4726KHPFK3LNMCSYJZ3YT7A2BFMGKEQYRLLTA2TSODUK3HBK2MOB